application: minihorse-990
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static
  static_dir: static
  
# all url handlers are admin-access unless included in the beginning of this list:
- url: /_ah/mail/tabun@minihorse-990\.appspotmail\.com
  script: main.app
- url: /_ah/mail/.*
  script: main.app
- url: /
  script: main.app
- url: .*
  script: main.app
  login: admin

libraries:
- name: webapp2
  version: "2.5.2"
- name: lxml
  version: "latest" # Even though Tabun API requires lxml-3.3, and App Engine Runtime only provides 2.3.5, this will hopefully work for some cases
- name: jinja2
  version: latest

inbound_services:
- mail